const gameState={running:false,round:0,total:20,score:0,correct:0,streak:0,bestStreak:0,start:0,times:[],current:null,pool:[],countdownTimer:null};
const pinyinState={running:false,round:0,total:20,score:0,correct:0,streak:0,bestStreak:0,start:0,times:[],current:null,pool:[],countdownTimer:null};

const gamesPanel=document.createElement('section');gamesPanel.className='gamesPanel';gamesPanel.innerHTML=`<div class="gamesHeading"><div><h2>Games</h2><p>Build instant recognition from multiple directions.</p></div><span class="gameBadge">2 GAMES</span></div><button id="characterRushButton" class="gameLaunch"><span><strong>Character Rush</strong><small>Character → meaning · reaction time</small></span><span>⚡</span></button><button id="pinyinRushButton" class="gameLaunch gameLaunchAlt"><span><strong>Pinyin Rush</strong><small>Pinyin → character · reaction time</small></span><span>拼</span></button>`;
if(typeof practiceTab!=='undefined')practiceTab.appendChild(gamesPanel);

const rushScreen=document.createElement('div');rushScreen.id='rushScreen';rushScreen.className='hidden';rushScreen.innerHTML=`<button id="rushBackButton" class="backButton">← Practice</button><div class="rushTop"><div><span>Score</span><strong id="rushScore">0</strong></div><div><span>Streak</span><strong id="rushStreak">0</strong></div><div><span>Question</span><strong><span id="rushNumber">1</span>/20</strong></div></div><div class="rushTimer"><div id="rushTimerBar"></div></div><div class="rushCard"><div id="rushCharacter" class="rushCharacter">我</div><p>Tap the meaning</p><div id="rushAnswers" class="rushAnswers"></div><div id="rushReaction" class="rushReaction"></div></div><div id="rushCountdown" class="rushCountdown hidden"><div id="rushCountdownNumber">3</div><span>Get ready!</span></div>`;document.querySelector('.app').appendChild(rushScreen);if(typeof screens!=='undefined')screens.push(rushScreen);

const rushResult=document.createElement('div');rushResult.id='rushResult';rushResult.className='hidden';rushResult.innerHTML=`<button id="rushResultBack" class="backButton">← Practice</button><h1>Character Rush</h1><div class="rushResultCard"><div class="rushFinalScore" id="rushFinalScore">0</div><span>points</span><div class="rushStats"><div><strong id="rushAccuracy">0%</strong><span>accuracy</span></div><div><strong id="rushAverage">—</strong><span>avg reaction</span></div><div><strong id="rushBest">—</strong><span>best reaction</span></div><div><strong id="rushBestStreak">0</strong><span>best streak</span></div></div></div><button id="rushPlayAgain">Play Again</button>`;document.querySelector('.app').appendChild(rushResult);if(typeof screens!=='undefined')screens.push(rushResult);

const pinyinScreen=document.createElement('div');pinyinScreen.id='pinyinRushScreen';pinyinScreen.className='hidden';pinyinScreen.innerHTML=`<button id="pinyinBackButton" class="backButton">← Practice</button><div class="rushTop"><div><span>Score</span><strong id="pinyinScore">0</strong></div><div><span>Streak</span><strong id="pinyinStreak">0</strong></div><div><span>Question</span><strong><span id="pinyinNumber">1</span>/20</strong></div></div><div class="rushTimer"><div id="pinyinTimerBar"></div></div><div class="rushCard"><div id="pinyinPrompt" class="pinyinRushPrompt">wǒ</div><p>Tap the character</p><div id="pinyinAnswers" class="rushAnswers pinyinAnswers"></div><div id="pinyinReaction" class="rushReaction"></div></div><div id="pinyinCountdown" class="rushCountdown hidden"><div id="pinyinCountdownNumber">3</div><span>Get ready!</span></div>`;document.querySelector('.app').appendChild(pinyinScreen);if(typeof screens!=='undefined')screens.push(pinyinScreen);

const pinyinResult=document.createElement('div');pinyinResult.id='pinyinRushResult';pinyinResult.className='hidden';pinyinResult.innerHTML=`<button id="pinyinResultBack" class="backButton">← Practice</button><h1>Pinyin Rush</h1><div class="rushResultCard"><div class="rushFinalScore" id="pinyinFinalScore">0</div><span>points</span><div class="rushStats"><div><strong id="pinyinAccuracy">0%</strong><span>accuracy</span></div><div><strong id="pinyinAverage">—</strong><span>avg reaction</span></div><div><strong id="pinyinBest">—</strong><span>best reaction</span></div><div><strong id="pinyinBestStreak">0</strong><span>best streak</span></div></div></div><button id="pinyinPlayAgain">Play Again</button>`;document.querySelector('.app').appendChild(pinyinResult);if(typeof screens!=='undefined')screens.push(pinyinResult);

function rushPool(){const unlocked=lessons.filter(l=>isLessonComplete(l.lessonNumber)).flatMap(l=>l.characters);return unlocked.length>=5?unlocked:lessons[0].characters;}
function rushShuffle(a){return [...a].sort(()=>Math.random()-.5);}
function runCountdown(state,countdownId,numberId,cardSelector,onGo){clearInterval(state.countdownTimer);state.running=false;document.querySelector(cardSelector)?.classList.add('rushWaiting');const countdown=document.getElementById(countdownId);const number=document.getElementById(numberId);countdown.classList.remove('hidden');let count=3;number.textContent=count;number.classList.remove('countPop');void number.offsetWidth;number.classList.add('countPop');state.countdownTimer=setInterval(()=>{count--;if(count>0){number.textContent=count;number.classList.remove('countPop');void number.offsetWidth;number.classList.add('countPop');return;}clearInterval(state.countdownTimer);number.textContent='GO!';number.classList.remove('countPop');void number.offsetWidth;number.classList.add('countPop');setTimeout(()=>{countdown.classList.add('hidden');document.querySelector(cardSelector)?.classList.remove('rushWaiting');state.running=true;onGo();},450);},850);}
function resetGameState(state){state.running=false;state.round=0;state.score=0;state.correct=0;state.streak=0;state.bestStreak=0;state.times=[];state.current=null;state.pool=rushPool();}

function startCharacterRush(){resetGameState(gameState);showScreen(rushScreen);document.getElementById('rushScore').textContent='0';document.getElementById('rushStreak').textContent='0';document.getElementById('rushNumber').textContent='1';document.getElementById('rushTimerBar').style.animation='none';runCountdown(gameState,'rushCountdown','rushCountdownNumber','#rushScreen .rushCard',nextRushQuestion);}
function nextRushQuestion(){if(gameState.round>=gameState.total){finishRush();return;}const pool=gameState.pool;let next=rushShuffle(pool)[0];if(gameState.current&&pool.length>1){while(next.symbol===gameState.current.symbol)next=rushShuffle(pool)[0];}gameState.current=next;gameState.round++;document.getElementById('rushNumber').textContent=gameState.round;document.getElementById('rushScore').textContent=gameState.score.toLocaleString();document.getElementById('rushStreak').textContent=gameState.streak;document.getElementById('rushCharacter').textContent=next.symbol;document.getElementById('rushReaction').textContent='';const wrong=rushShuffle(pool.filter(x=>x.meaning!==next.meaning)).slice(0,3).map(x=>x.meaning);const choices=rushShuffle([next.meaning,...wrong]);const box=document.getElementById('rushAnswers');box.innerHTML='';choices.forEach(choice=>{const b=document.createElement('button');b.className='rushAnswer';b.textContent=choice;b.onclick=()=>answerRush(b,choice);box.appendChild(b);});const bar=document.getElementById('rushTimerBar');bar.style.animation='none';void bar.offsetWidth;bar.style.animation='rushDrain 5s linear forwards';gameState.start=performance.now();}
function answerRush(button,choice){if(!gameState.running)return;const elapsed=performance.now()-gameState.start;const correct=choice===gameState.current.meaning;gameState.running=false;document.getElementById('rushTimerBar').style.animationPlayState='paused';document.querySelectorAll('#rushAnswers .rushAnswer').forEach(b=>{b.disabled=true;if(b.textContent===gameState.current.meaning)b.classList.add('correct');});if(correct){gameState.correct++;gameState.streak++;gameState.bestStreak=Math.max(gameState.bestStreak,gameState.streak);gameState.times.push(elapsed);const speed=Math.max(100,Math.round(1200-elapsed*.25));const streakBonus=Math.min(500,gameState.streak*35);gameState.score+=speed+streakBonus;button.classList.add('correct');document.getElementById('rushReaction').textContent=`✓ ${(elapsed/1000).toFixed(2)} s  +${speed+streakBonus}`;}else{gameState.streak=0;button.classList.add('incorrect');document.getElementById('rushReaction').textContent=`✕ ${gameState.current.meaning}`;}document.getElementById('rushScore').textContent=gameState.score.toLocaleString();document.getElementById('rushStreak').textContent=gameState.streak;setTimeout(()=>{gameState.running=true;nextRushQuestion();},650);}
function finishRush(){gameState.running=false;showScreen(rushResult);const accuracy=Math.round(gameState.correct/gameState.total*100);const avg=gameState.times.length?gameState.times.reduce((a,b)=>a+b,0)/gameState.times.length:null;const best=gameState.times.length?Math.min(...gameState.times):null;document.getElementById('rushFinalScore').textContent=gameState.score.toLocaleString();document.getElementById('rushAccuracy').textContent=`${accuracy}%`;document.getElementById('rushAverage').textContent=avg?`${(avg/1000).toFixed(2)} s`:'—';document.getElementById('rushBest').textContent=best?`${(best/1000).toFixed(2)} s`:'—';document.getElementById('rushBestStreak').textContent=gameState.bestStreak;const old=JSON.parse(localStorage.getItem('characterRushBest')||'{}');if(!old.score||gameState.score>old.score)localStorage.setItem('characterRushBest',JSON.stringify({score:gameState.score,accuracy,avg,best,streak:gameState.bestStreak,date:new Date().toISOString()}));}

function startPinyinRush(){resetGameState(pinyinState);showScreen(pinyinScreen);document.getElementById('pinyinScore').textContent='0';document.getElementById('pinyinStreak').textContent='0';document.getElementById('pinyinNumber').textContent='1';document.getElementById('pinyinTimerBar').style.animation='none';runCountdown(pinyinState,'pinyinCountdown','pinyinCountdownNumber','#pinyinRushScreen .rushCard',nextPinyinQuestion);}
function nextPinyinQuestion(){if(pinyinState.round>=pinyinState.total){finishPinyinRush();return;}const pool=pinyinState.pool;let next=rushShuffle(pool)[0];if(pinyinState.current&&pool.length>1){while(next.symbol===pinyinState.current.symbol)next=rushShuffle(pool)[0];}pinyinState.current=next;pinyinState.round++;document.getElementById('pinyinNumber').textContent=pinyinState.round;document.getElementById('pinyinScore').textContent=pinyinState.score.toLocaleString();document.getElementById('pinyinStreak').textContent=pinyinState.streak;document.getElementById('pinyinPrompt').textContent=next.pinyin;document.getElementById('pinyinReaction').textContent='';const wrong=rushShuffle(pool.filter(x=>x.symbol!==next.symbol)).slice(0,3).map(x=>x.symbol);const choices=rushShuffle([next.symbol,...wrong]);const box=document.getElementById('pinyinAnswers');box.innerHTML='';choices.forEach(choice=>{const b=document.createElement('button');b.className='rushAnswer pinyinRushAnswer';b.textContent=choice;b.onclick=()=>answerPinyinRush(b,choice);box.appendChild(b);});const bar=document.getElementById('pinyinTimerBar');bar.style.animation='none';void bar.offsetWidth;bar.style.animation='rushDrain 5s linear forwards';pinyinState.start=performance.now();}
function answerPinyinRush(button,choice){if(!pinyinState.running)return;const elapsed=performance.now()-pinyinState.start;const correct=choice===pinyinState.current.symbol;pinyinState.running=false;document.getElementById('pinyinTimerBar').style.animationPlayState='paused';document.querySelectorAll('#pinyinAnswers .rushAnswer').forEach(b=>{b.disabled=true;if(b.textContent===pinyinState.current.symbol)b.classList.add('correct');});if(correct){pinyinState.correct++;pinyinState.streak++;pinyinState.bestStreak=Math.max(pinyinState.bestStreak,pinyinState.streak);pinyinState.times.push(elapsed);const speed=Math.max(100,Math.round(1200-elapsed*.25));const streakBonus=Math.min(500,pinyinState.streak*35);pinyinState.score+=speed+streakBonus;button.classList.add('correct');document.getElementById('pinyinReaction').textContent=`✓ ${(elapsed/1000).toFixed(2)} s  +${speed+streakBonus}`;}else{pinyinState.streak=0;button.classList.add('incorrect');document.getElementById('pinyinReaction').textContent=`✕ ${pinyinState.current.symbol} = ${pinyinState.current.meaning}`;}document.getElementById('pinyinScore').textContent=pinyinState.score.toLocaleString();document.getElementById('pinyinStreak').textContent=pinyinState.streak;setTimeout(()=>{pinyinState.running=true;nextPinyinQuestion();},650);}
function finishPinyinRush(){pinyinState.running=false;showScreen(pinyinResult);const accuracy=Math.round(pinyinState.correct/pinyinState.total*100);const avg=pinyinState.times.length?pinyinState.times.reduce((a,b)=>a+b,0)/pinyinState.times.length:null;const best=pinyinState.times.length?Math.min(...pinyinState.times):null;document.getElementById('pinyinFinalScore').textContent=pinyinState.score.toLocaleString();document.getElementById('pinyinAccuracy').textContent=`${accuracy}%`;document.getElementById('pinyinAverage').textContent=avg?`${(avg/1000).toFixed(2)} s`:'—';document.getElementById('pinyinBest').textContent=best?`${(best/1000).toFixed(2)} s`:'—';document.getElementById('pinyinBestStreak').textContent=pinyinState.bestStreak;const old=JSON.parse(localStorage.getItem('pinyinRushBest')||'{}');if(!old.score||pinyinState.score>old.score)localStorage.setItem('pinyinRushBest',JSON.stringify({score:pinyinState.score,accuracy,avg,best,streak:pinyinState.bestStreak,date:new Date().toISOString()}));}

function exitGames(){clearInterval(gameState.countdownTimer);clearInterval(pinyinState.countdownTimer);gameState.running=false;pinyinState.running=false;if('speechSynthesis'in window)window.speechSynthesis.cancel();showHome();if(typeof switchTab==='function')switchTab('practice');}
document.getElementById('characterRushButton').onclick=startCharacterRush;document.getElementById('pinyinRushButton').onclick=startPinyinRush;document.getElementById('rushPlayAgain').onclick=startCharacterRush;document.getElementById('pinyinPlayAgain').onclick=startPinyinRush;document.getElementById('rushBackButton').onclick=exitGames;document.getElementById('rushResultBack').onclick=exitGames;document.getElementById('pinyinBackButton').onclick=exitGames;document.getElementById('pinyinResultBack').onclick=exitGames;
