const gameState={running:false,round:0,total:20,score:0,correct:0,streak:0,bestStreak:0,start:0,times:[],current:null,pool:[]};

const gamesPanel=document.createElement('section');gamesPanel.className='gamesPanel';gamesPanel.innerHTML=`<div class="gamesHeading"><div><h2>Games</h2><p>Build instant character recognition.</p></div><span class="gameBadge">NEW</span></div><button id="characterRushButton" class="gameLaunch"><span><strong>Character Rush</strong><small>20 questions · meaning recognition · reaction time</small></span><span>⚡</span></button>`;
if(typeof practiceTab!=='undefined')practiceTab.appendChild(gamesPanel);

const rushScreen=document.createElement('div');rushScreen.id='rushScreen';rushScreen.className='hidden';rushScreen.innerHTML=`<button id="rushBackButton" class="backButton">← Practice</button><div class="rushTop"><div><span>Score</span><strong id="rushScore">0</strong></div><div><span>Streak</span><strong id="rushStreak">0</strong></div><div><span>Question</span><strong><span id="rushNumber">1</span>/20</strong></div></div><div class="rushTimer"><div id="rushTimerBar"></div></div><div class="rushCard"><div id="rushCharacter" class="rushCharacter">我</div><p>Tap the meaning</p><div id="rushAnswers" class="rushAnswers"></div><div id="rushReaction" class="rushReaction"></div></div>`;document.querySelector('.app').appendChild(rushScreen);if(typeof screens!=='undefined')screens.push(rushScreen);

const rushResult=document.createElement('div');rushResult.id='rushResult';rushResult.className='hidden';rushResult.innerHTML=`<button id="rushResultBack" class="backButton">← Practice</button><h1>Character Rush</h1><div class="rushResultCard"><div class="rushFinalScore" id="rushFinalScore">0</div><span>points</span><div class="rushStats"><div><strong id="rushAccuracy">0%</strong><span>accuracy</span></div><div><strong id="rushAverage">—</strong><span>avg reaction</span></div><div><strong id="rushBest">—</strong><span>best reaction</span></div><div><strong id="rushBestStreak">0</strong><span>best streak</span></div></div></div><button id="rushPlayAgain">Play Again</button>`;document.querySelector('.app').appendChild(rushResult);if(typeof screens!=='undefined')screens.push(rushResult);

function rushPool(){const unlocked=lessons.filter(l=>isLessonComplete(l.lessonNumber)).flatMap(l=>l.characters);return unlocked.length>=5?unlocked:lessons[0].characters;}
function rushShuffle(a){return [...a].sort(()=>Math.random()-.5);}
function startCharacterRush(){gameState.running=true;gameState.round=0;gameState.score=0;gameState.correct=0;gameState.streak=0;gameState.bestStreak=0;gameState.times=[];gameState.pool=rushPool();showScreen(rushScreen);nextRushQuestion();}
function nextRushQuestion(){if(gameState.round>=gameState.total){finishRush();return;}const pool=gameState.pool;let next=rushShuffle(pool)[0];if(gameState.current&&pool.length>1){while(next.symbol===gameState.current.symbol)next=rushShuffle(pool)[0];}gameState.current=next;gameState.round++;document.getElementById('rushNumber').textContent=gameState.round;document.getElementById('rushScore').textContent=gameState.score.toLocaleString();document.getElementById('rushStreak').textContent=gameState.streak;document.getElementById('rushCharacter').textContent=next.symbol;document.getElementById('rushReaction').textContent='';const wrong=rushShuffle(pool.filter(x=>x.meaning!==next.meaning)).slice(0,3).map(x=>x.meaning);const choices=rushShuffle([next.meaning,...wrong]);const box=document.getElementById('rushAnswers');box.innerHTML='';choices.forEach(choice=>{const b=document.createElement('button');b.className='rushAnswer';b.textContent=choice;b.onclick=()=>answerRush(b,choice);box.appendChild(b);});const bar=document.getElementById('rushTimerBar');bar.style.animation='none';void bar.offsetWidth;bar.style.animation='rushDrain 5s linear forwards';gameState.start=performance.now();}
function answerRush(button,choice){if(!gameState.running)return;const elapsed=performance.now()-gameState.start;const correct=choice===gameState.current.meaning;gameState.running=false;document.getElementById('rushTimerBar').style.animationPlayState='paused';document.querySelectorAll('.rushAnswer').forEach(b=>{b.disabled=true;if(b.textContent===gameState.current.meaning)b.classList.add('correct');});if(correct){gameState.correct++;gameState.streak++;gameState.bestStreak=Math.max(gameState.bestStreak,gameState.streak);gameState.times.push(elapsed);const speed=Math.max(100,Math.round(1200-elapsed*.25));const streakBonus=Math.min(500,gameState.streak*35);gameState.score+=speed+streakBonus;button.classList.add('correct');document.getElementById('rushReaction').textContent=`✓ ${(elapsed/1000).toFixed(2)} s  +${speed+streakBonus}`;}else{gameState.streak=0;button.classList.add('incorrect');document.getElementById('rushReaction').textContent=`✕ ${gameState.current.meaning}`;}document.getElementById('rushScore').textContent=gameState.score.toLocaleString();document.getElementById('rushStreak').textContent=gameState.streak;setTimeout(()=>{gameState.running=true;nextRushQuestion();},650);}
function finishRush(){gameState.running=false;showScreen(rushResult);const accuracy=Math.round(gameState.correct/gameState.total*100);const avg=gameState.times.length?gameState.times.reduce((a,b)=>a+b,0)/gameState.times.length:null;const best=gameState.times.length?Math.min(...gameState.times):null;document.getElementById('rushFinalScore').textContent=gameState.score.toLocaleString();document.getElementById('rushAccuracy').textContent=`${accuracy}%`;document.getElementById('rushAverage').textContent=avg?`${(avg/1000).toFixed(2)} s`:'—';document.getElementById('rushBest').textContent=best?`${(best/1000).toFixed(2)} s`:'—';document.getElementById('rushBestStreak').textContent=gameState.bestStreak;const old=JSON.parse(localStorage.getItem('characterRushBest')||'{}');if(!old.score||gameState.score>old.score)localStorage.setItem('characterRushBest',JSON.stringify({score:gameState.score,accuracy,avg,best,streak:gameState.bestStreak,date:new Date().toISOString()}));}
function exitRush(){gameState.running=false;if('speechSynthesis'in window)window.speechSynthesis.cancel();showHome();if(typeof switchTab==='function')switchTab('practice');}
document.getElementById('characterRushButton').onclick=startCharacterRush;document.getElementById('rushPlayAgain').onclick=startCharacterRush;document.getElementById('rushBackButton').onclick=exitRush;document.getElementById('rushResultBack').onclick=exitRush;
