const grammarLessons = [
  {n:1,requires:1,title:"Basic Word Order",summary:"Mandarin often follows Subject + Verb + Object, much like English.",rules:["Put the person or thing doing the action first.","Mandarin verbs do not change for I, you, or he/she."],examples:[{zh:"我是人。",py:"wǒ shì rén.",en:"I am a person.",parts:"我 (I) + 是 (am/is) + 人 (person)"}]},
  {n:2,requires:2,title:"Negation with 不",summary:"Put 不 before a verb or adjective to make it negative.",rules:["不 usually comes directly before what it negates.","不是 means ‘is not / am not / are not’."],examples:[{zh:"我不是他。",py:"wǒ bú shì tā.",en:"I am not him.",parts:"我 + 不 + 是 + 他"}]},
  {n:3,requires:3,title:"Location & Description",summary:"在 marks location, while descriptive words can function without an English-style ‘is’ in many sentences.",rules:["Subject + 在 + place expresses where something is.","这 and 那 mean this and that."],examples:[{zh:"他在这。",py:"tā zài zhè.",en:"He is here.",parts:"他 (he) + 在 (at) + 这 (here/this)"}]},
  {n:4,requires:4,title:"Direction & Verb Compounds",summary:"来 and 去 show movement toward or away from the speaker and combine with direction words.",rules:["上来 = come up; 下来 = come down.","上去 = go up; 下去 = go down."],examples:[{zh:"他下来。",py:"tā xiàlái.",en:"He comes down.",parts:"他 + 下 + 来"}]},
  {n:5,requires:5,title:"Building Compound Words",summary:"Chinese frequently combines characters to create a more specific word.",rules:["中 + 国 forms 中国 (China).","学 + 生 forms 学生 (student).","生 + 日 forms 生日 (birthday)."],examples:[{zh:"他是中国人。",py:"tā shì Zhōngguó rén.",en:"He is Chinese.",parts:"他 + 是 + 中国 + 人"}]},
  {n:6,requires:6,title:"Questions & 的",summary:"吗 turns a statement into a yes/no question. 的 commonly marks possession or description.",rules:["Statement + 吗？ creates a yes/no question.","Owner + 的 expresses possession: 我的 = my/mine.","谁 asks ‘who’; 什么 asks ‘what’."],examples:[{zh:"你是学生吗？",py:"nǐ shì xuéshēng ma?",en:"Are you a student?",parts:"你 + 是 + 学生 + 吗"},{zh:"这是谁的？",py:"zhè shì shéi de?",en:"Whose is this?",parts:"这 + 是 + 谁 + 的"}]},
  {n:7,requires:7,title:"Numbers & Measure Words",summary:"A number normally needs a measure word before a noun. 个 is the most common general measure word.",rules:["Number + measure word + noun is the standard pattern.","Use 两 rather than 二 before many measure words in natural speech; 两个 = two items/people."],examples:[{zh:"我有三个。",py:"wǒ yǒu sān ge.",en:"I have three.",parts:"我 + 有 + 三 + 个"}]},
  {n:8,requires:8,title:"Time Comes Early",summary:"Time expressions usually appear before the verb, often after the subject.",rules:["A common pattern is Subject + Time + Verb + Object.","今天 means today; 今年 means this year."],examples:[{zh:"我今天回家。",py:"wǒ jīntiān huí jiā.",en:"I am going home today.",parts:"我 + 今天 + 回家"}]},
  {n:9,requires:9,title:"会, 能 & 想",summary:"Mandarin uses modal verbs before the main verb to express ability, possibility, or desire.",rules:["会 often means a learned ability: 会说 = can speak.","能 often means being able to because circumstances allow it.","想 + verb often means want to / would like to."],examples:[{zh:"我会说。",py:"wǒ huì shuō.",en:"I can speak.",parts:"我 + 会 + 说"},{zh:"你想看吗？",py:"nǐ xiǎng kàn ma?",en:"Do you want to watch?",parts:"你 + 想 + 看 + 吗"}]},
  {n:10,requires:10,title:"要, 想 & Verb Chains",summary:"Mandarin can place verbs together without adding English words like ‘to’ between them.",rules:["想 is often a softer ‘want/would like’; 要 can be stronger: want, need, or going to.","Modal + action: 我要回家 literally follows I + want/need + return + home."],examples:[{zh:"我要回家。",py:"wǒ yào huí jiā.",en:"I want to go home.",parts:"我 + 要 + 回 + 家"},{zh:"你能做吗？",py:"nǐ néng zuò ma?",en:"Can you do it?",parts:"你 + 能 + 做 + 吗"}]}
];

const grammarPanel=document.createElement("section");grammarPanel.className="grammarPanel";grammarPanel.innerHTML=`<div><h2>Grammar Guide</h2><p>Learn why Mandarin sentences work the way they do.</p></div><button id="openGrammarButton">Open Guide</button>`;
const characterHeading=[...homeScreen.querySelectorAll("h2")].find(h=>h.textContent.trim()==="Character Lessons");homeScreen.insertBefore(grammarPanel,characterHeading);
const grammarScreen=document.createElement("div");grammarScreen.id="grammarScreen";grammarScreen.className="hidden";grammarScreen.innerHTML=`<button id="grammarBackButton" class="backButton">← Home</button><h1>Grammar Guide</h1><p class="grammarIntro">Short lessons unlock alongside your character lessons.</p><div id="grammarLessonList"></div>`;document.querySelector(".app").appendChild(grammarScreen);screens.push(grammarScreen);
const grammarDetail=document.createElement("div");grammarDetail.id="grammarDetail";grammarDetail.className="hidden";grammarDetail.innerHTML=`<button id="grammarDetailBack" class="backButton">← Grammar Guide</button><div id="grammarContent"></div>`;document.querySelector(".app").appendChild(grammarDetail);screens.push(grammarDetail);
function grammarUnlocked(g){return g.requires===1||isLessonComplete(g.requires-1)||isLessonComplete(g.requires)}
function renderGrammar(){const list=document.getElementById("grammarLessonList");list.innerHTML="";grammarLessons.forEach(g=>{const unlocked=grammarUnlocked(g);const b=document.createElement("button");b.className=`lessonButton grammarLessonButton ${unlocked?"":"locked"}`;b.innerHTML=`<span class="lessonTopline"><strong>Grammar ${g.n}</strong><span>${unlocked?"→":"🔒"}</span></span><span class="lessonTitleText">${g.title}</span><small>${unlocked?g.summary:`Complete Character Lesson ${Math.max(1,g.requires-1)} to unlock`}</small>`;if(unlocked)b.onclick=()=>openGrammar(g);list.appendChild(b)})}
function openGrammar(g){showScreen(grammarDetail);const c=document.getElementById("grammarContent");c.innerHTML=`<div class="grammarHeader"><span>Grammar ${g.n}</span><h1>${g.title}</h1><p>${g.summary}</p></div><div class="grammarRuleCard"><h2>How it works</h2>${g.rules.map(r=>`<p>• ${r}</p>`).join("")}</div><h2 class="exampleHeading">Examples</h2>${g.examples.map(e=>`<div class="grammarExample"><div class="grammarChinese">${e.zh}</div><div class="grammarPinyin">${e.py}</div><div class="grammarEnglish">${e.en}</div><div class="grammarParts">${e.parts}</div></div>`).join("")}<button id="grammarPracticeLink">Practice What You've Learned</button>`;document.getElementById("grammarPracticeLink").onclick=()=>{if(g.requires>=6&&typeof startSentencePractice==="function")startSentencePractice();else showHome()}}
document.getElementById("openGrammarButton").onclick=()=>{renderGrammar();showScreen(grammarScreen)};document.getElementById("grammarBackButton").onclick=showHome;document.getElementById("grammarDetailBack").onclick=()=>{renderGrammar();showScreen(grammarScreen)};
